# Generated by Django 4.2.16 on 2025-01-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='client',
        ),
        migrations.RemoveField(
            model_name='review',
            name='project',
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(max_length=100),
        ),
    ]
