# Generated by Django 4.2.16 on 2025-01-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_client_remove_review_project_and_more'),
        ('reviews', '0003_alter_review_reviewer_name'),
    ]

    operations = [
    ]
